import dns.zone
import dns.rdatatype
import dns.name
from typing import List
from . import schemas, models

def parse_bind_zone(zone_text: str, origin_domain: str) -> List[schemas.DNSRecordCreate]:
    """Parse BIND zone text and return a list of DNSRecordCreate schemas"""
    # Ensure origin_domain ends with a dot
    if not origin_domain.endswith("."):
        origin_domain += "."
        
    try:
        # Parse the zone from text
        zone = dns.zone.from_text(zone_text, origin=origin_domain, relativize=False)
    except Exception as e:
        raise ValueError(f"Failed to parse BIND zone file: {str(e)}")
        
    records = []
    for name, node in zone.nodes.items():
        record_name = str(name)
        for rdataset in node.rdatasets:
            rtype = dns.rdatatype.to_text(rdataset.rdtype)
            ttl = rdataset.ttl
            
            # Extract all values for this record
            values = []
            for rdata in rdataset:
                values.append(rdata.to_text())
                
            if values:
                record_val = "\n".join(values)
                
                # Skip SOA records since they are managed automatically by Route53
                if rtype == "SOA":
                    continue
                # If it's an NS record at the origin domain, skip it to avoid overwriting default NS servers
                if rtype == "NS" and record_name == origin_domain:
                    continue
                    
                records.append(schemas.DNSRecordCreate(
                    name=record_name,
                    type=rtype,
                    routing_policy="Simple",
                    ttl=ttl,
                    value=record_val,
                    alias=False
                ))
    return records

def export_to_bind(zone_name: str, records: List[models.DNSRecord]) -> str:
    """Generate a BIND zone file representation of a hosted zone's records"""
    lines = []
    lines.append(f";; BIND Zone File for {zone_name}")
    lines.append(f";; Generated by Route53 Clone")
    lines.append(f"$ORIGIN {zone_name}")
    lines.append("")
    
    # Sort records: SOA first, then NS, then others
    sorted_records = sorted(
        records,
        key=lambda r: (0 if r.type == "SOA" else 1 if r.type == "NS" else 2, r.name, r.type)
    )
    
    for r in sorted_records:
        name_str = r.name
        if name_str == zone_name:
            name_str = "@"
        elif name_str.endswith("." + zone_name):
            name_str = name_str[:-len("." + zone_name)]
            if name_str == "":
                name_str = "@"
                
        vals = r.value.split("\n")
        for val in vals:
            if r.alias:
                lines.append(f"; Alias target to: {r.alias_target}")
                lines.append(f"{name_str}\t{r.ttl}\tIN\t{r.type}\t{r.alias_target}")
            else:
                # Add quotes around TXT values if they don't already have them
                formatted_val = val
                if r.type == "TXT" and not (val.startswith('"') and val.endswith('"')):
                    formatted_val = f'"{val}"'
                lines.append(f"{name_str}\t{r.ttl}\tIN\t{r.type}\t{formatted_val}")
                
    return "\n".join(lines)
